FROM zaha/golang
MAINTAINER Tony Worm docker@zaha.io

# Other services
RUN go get github.com/jinzhu/gorm
RUN go get github.com/jmcvetta/neoism
RUN go get github.com/zemirco/couchdb
RUN go get github.com/gocql/gocql
RUN go get gopkg.in/redis.v2
RUN go get github.com/streadway/amqp

RUN go get github.com/ant0ine/go-json-rest/rest

